# Generated by Django 3.0.4 on 2020-09-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donate_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=320)),
                ('amount', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'DONATIONS',
            },
        ),
        migrations.CreateModel(
            name='transaction_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_by', models.CharField(max_length=200)),
                ('made_on', models.DateField(max_length=50)),
                ('amount', models.BigIntegerField()),
                ('order_id', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
